### ISSUE TITLE
Seed Development DB with Remote DB content

### ISSUE THREAD

**Issue by spinozist** [atlregional/datanexus-updater#1]
Individually create and populate these collections with current data:
- [x] dataAPIs
- [x] geoAPIs
- [x] defaultConfigs
- [x] tileLayers
- [x] dataManifests

**Comment by hermanjohn2** [comment]
@spinozist Got my DB seeded. Might have went a little overboard with all the code I wrote, but there might be a few snippets that will come in handy later on with this project. 

Branch: update-urls

**Comment by spinozist** [comment]
Looks great.  I made a few small changes by modularizing some functions and creating a seedDB.js file for the code you wrote.  Thanks!!
