### ISSUE TITLE
Add New Dataset

### ISSUE THREAD

**Issue by spinozist** [atlregional/datanexus-updater#2]
Reference files in corresponding folders using ```process.argv``` to run the following database operations in order
- [x] insert into dataAPIs
- [x] update by id the dataAPIs property (from list of dataAPI key that were just inserted) looping over the following geoAPI ids:
```
[
    "state",
    "counties",
    "gazcta",
    "cities",
    "gahouse",
    "gasenate",
    "gatracts",
    "coanpu",
    "coansa",
    "uscongress",
    "rc",
    "superdistrict",
    "arctracts",
    "arczcta"
  ]
```
- [x] insert all records into dataManifest
- [x] update the dataAPIs property in defaultConfig by adding list of dataAPI key just added

## Example CLI
- adding multiple geos
```node addNewDataset.js dataAPI.json manifest.json geoUpdateList.json```
- adding to just one geo
```node addNewDataset.js dataAPI.json manifest.json counties```

**Comment by hermanjohn2** [comment]
@spinozist Pushed changes to AddNewDataSet.js. When you have time, please take a look and let us know what you think. I can demo tomorrow, if you'd like.

@TJFitz pull down and apply some of those query changes you were working on, if you want!

Branch: add-data-set

**Comment by spinozist** [comment]
Great! Can you demo this afternoon?

**Comment by hermanjohn2** [comment]
@spinozist Yea! I'm free anytime outside of 12pm-1:05pm. Let me know what's best for you.

**Comment by spinozist** [comment]
I'll send a calendar invite for 1:30 to 2:30.  That should be enough time to review and demo the code as well as discuss next issues.
