### ISSUE TITLE
Insert Document(s) into Collection Node App

### ISSUE THREAD

**Issue by spinozist** [atlregional/datanexus-updater#4]
Create Node App to take in ```collection name``` and ```source filename``` and then insert record(s) in source file into collection.

Example command line:
```node InsertIntoCollection.js geoapis newGeoAPIs.json```

Test on:
- [x] geoAPIs
- [x] dataAPIs
- [x] defaultConfigs
- [x] tileLayers
- [x] manifests

**Comment by TJFitz** [comment]
Hey Erik I've got the app running properly, can demo anytime if you'd like but its very simple, essentially what John and I constructed the other day.

**Comment by spinozist** [comment]
Great!  Can you meet at 11 today for a quick demo and review of the code?

On Feb 17, 2021, at 8:41 PM, TJFitz <notifications@github.com> wrote:

﻿

Hey Erik I've got the app running properly, can demo anytime if you'd like but its very simple, essentially what John and I constructed the other day.

**Comment by spinozist** [comment]
How about this afternoon after 4?

Erik Woodworth
ewoodworth@atlantaregional.org

From: Erik Woodworth <EWoodworth@atlantaregional.org>
Date: Thursday, February 18, 2021 at 8:21 AM
To: atlregional/datanexus-updater <reply@reply.github.com>
Cc: atlregional/datanexus-updater <datanexus-updater@noreply.github.com>, Author <author@noreply.github.com>
Subject: Re: [atlregional/datanexus-updater] Insert Document(s) into Collection Node App (#4)
Great!  Can you meet at 11 today for a quick demo and review of the code?
On Feb 17, 2021, at 8:41 PM, TJFitz <notifications@github.com> wrote:
﻿

Hey Erik I've got the app running properly, can demo anytime if you'd like but its very simple, essentially what John and I constructed the other day.

**Comment by TJFitz** [comment]
Goodness I just woke up I'm so sorry! 4 works fine for me

**Comment by spinozist** [comment]
No worries at all.  I’ll send an invite for 4.

Also, did you get the invite I sent for this afternoon’s staff meeting?  It’s totally optional for you to attend, but I wanted to give you the opportunity if you’d like to be there.


On Feb 18, 2021, at 11:12 AM, TJFitz <notifications@github.com> wrote:

﻿

Goodness I just woke up I'm so sorry! 4 works fine for me

**Comment by TJFitz** [comment]
Indeed I did, you'll see me there!

**Comment by spinozist** [comment]
I’m going to move our 4 o’clock up to 2:30 if that’s okay.

Erik Woodworth
ewoodworth@atlantaregional.org
